sudo: false

language: d
d:
- dmd
- ldc

os:
- linux
- osx

env:
- ARCH=x86_64 CONFIG=library
- ARCH=x86_64 CONFIG=minimal
- ARCH=x86_64 CONFIG=console
#- ARCH=x86 CONFIG=library
#- ARCH=x86 CONFIG=minimal
#- ARCH=x86 CONFIG=console

# No one cares about OS X x86
#matrix:
#  exclude:
#  - os: osx
#    env: ARCH=x86 CONFIG=library
#  - os: osx
#    env: ARCH=x86 CONFIG=minimal
#  - os: osx
#    env: ARCH=x86 CONFIG=console

branches:
  only:
  - master

addons:
  apt:
    packages:
    - gcc-multilib
    - libpixman-1-dev
    - libx11-dev
    - libxext-dev
    - zlib1g-dev
#    - libpixman-1-dev:i386
#    - libx11-dev:i386
#    - libxext-dev:i386
#    - zlib1g-dev:i386

script:
- dub test --compiler=${DC} --arch=${ARCH} --config=${CONFIG} --DRT-gcopt=parallel:0

jobs:
  include:
  - stage: deploy
    script: ./docs.sh
    deploy:
      local_dir: docs
      provider: pages
      skip_cleanup: true
      github_token: $GH_TOKEN
      on:
        branch: master

cache:
  directories:
  - $HOME/.dub
